from __future__ import annotations

import copy
from typing import Any, Dict


DEFAULT_CONFIG_V3: Dict[str, Any] = {
    "version": 3,
    "common": {
        "paths": {
            "business_root_dir": "D:\\QLDownload",
            "runtime_state_root": ".runtime",
        },
        "deployment": {
            "role_mode": "",
            "last_started_role_mode": "",
            "node_id": "",
            "node_label": "",
        },
        "shared_bridge": {
            "enabled": False,
            "root_dir": "",
            "internal_root_dir": "",
            "external_root_dir": "",
            "poll_interval_sec": 2,
            "heartbeat_interval_sec": 5,
            "claim_lease_sec": 30,
            "stale_task_timeout_sec": 1800,
            "artifact_retention_days": 7,
            "sqlite_busy_timeout_ms": 15000,
        },
        "internal_source_cache": {
            "enabled": True,
            "run_on_startup": True,
            "check_interval_sec": 30,
            "hour_bucket_mode": "natural_hour",
            "latest_required": True,
            "history_fill_timeout_sec": 1800,
        },
        "internal_source_sites": [
            {"building": "A楼", "enabled": False, "host": "", "username": "", "password": ""},
            {"building": "B楼", "enabled": False, "host": "", "username": "", "password": ""},
            {"building": "C楼", "enabled": False, "host": "", "username": "", "password": ""},
            {"building": "D楼", "enabled": False, "host": "", "username": "", "password": ""},
            {"building": "E楼", "enabled": False, "host": "", "username": "", "password": ""},
        ],
        "scheduler": {
            "enabled": True,
            "auto_start_in_gui": False,
            "interval_minutes": 60,
            "check_interval_sec": 30,
            "retry_failed_on_next_tick": True,
            "state_file": "daily_scheduler_state.json",
        },
        "notify": {
            "enable_webhook": True,
            "feishu_webhook_url": "",
            "keyword": "事件",
            "timeout": 10,
            "on_download_failure": True,
            "on_wifi_failure": True,
            "on_upload_failure": True,
        },
        "feishu_auth": {
            "app_id": "",
            "app_secret": "",
            "request_retry_count": 3,
            "request_retry_interval_sec": 2,
            "timeout": 30,
        },
        "updater": {
            "enabled": True,
            "check_interval_sec": 3600,
            "auto_apply": False,
            "auto_restart": True,
            "allow_downgrade": False,
            "gitee_repo": "https://gitee.com/myligitt/qjpt.git",
            "gitee_branch": "master",
            "gitee_subdir": "updates/patches",
            "gitee_manifest_path": "updates/latest_patch.json",
            "request_timeout_sec": 20,
            "download_retry_count": 3,
            "state_file": "updater_state.json",
            "download_dir": "runtime_state/updater/downloads",
            "backup_dir": "runtime_state/updater/backups",
            "max_backups": 3,
        },
        "console": {
            "enabled": True,
            "host": "0.0.0.0",
            "port": 18765,
            "auto_open_browser": True,
            "open_browser_delay_sec": 1,
            "ui_theme": "light",
            "log_buffer_size": 5000,
            "enable_sse": True,
        },
    },
    "features": {
        "monthly_report": {
            "buildings": ["A楼", "B楼", "C楼", "D楼", "E楼"],
            "file_glob_template": "{building}_*.xlsx",
            "time_range_mode": "yesterday_to_today_start",
            "custom_window_mode": "absolute",
            "start_time": "",
            "end_time": "",
            "daily_custom_window": {
                "start_time": "08:00:00",
                "end_time": "17:00:00",
                "cross_day": False,
            },
            "run_subdir_mode": "timestamp",
            "run_subdir_prefix": "run_",
            "max_retries": 3,
            "retry_wait_sec": 2,
            "site_start_delay_sec": 1,
            "only_process_downloaded_this_run": True,
            "browser_headless": True,
            "browser_channel": "chrome",
            "playwright_browsers_path": "",
            "sites": [],
            "multi_date": {
                "max_dates_per_run": 31,
            },
            "resume": {
                "enabled": True,
                "retention_days": 7,
                "auto_continue_when_external": True,
                "auto_continue_poll_sec": 5,
                "gc_every_n_items": 5,
                "upload_chunk_threshold": 20,
                "upload_chunk_size": 5,
                "root_dir": "pipeline_resume",
                "index_file": "index.json",
            },
            "performance": {
                "query_result_timeout_ms": 10000,
                "login_fill_timeout_ms": 5000,
                "start_end_visible_timeout_ms": 3000,
                "force_iframe_reopen_each_task": True,
                "page_refresh_retry_count": 1,
                "retry_failed_after_all_done": True,
                "retry_failed_max_rounds": 1,
            },
            "upload": {
                "enable_upload": True,
                "skip_zero_records": False,
                "date_field_mode": "timestamp",
                "date_field_day": 1,
                "date_tz_offset_hours": 8,
                "app_token": "",
                "calc_table_id": "",
                "attachment_table_id": "",
                "report_type": "全景平台月报",
            },
        },
        "sheet_import": {},
        "handover_log": {
            "enabled": True,
            "scheduler": {
                "enabled": True,
                "auto_start_in_gui": False,
                "morning_time": "07:00:00",
                "afternoon_time": "16:00:00",
                "check_interval_sec": 30,
                "catch_up_if_missed": False,
                "retry_failed_in_same_period": False,
                "morning_state_file": "handover_scheduler_morning_state.json",
                "afternoon_state_file": "handover_scheduler_afternoon_state.json",
            },
            "download": {
                "template_name": "交接班日志（李世龙）",
                "lookback_minutes": 20,
                "use_shift_window_when_provided": False,
                "shift_windows": {
                    "day": {"start": "08:00:00", "end": "17:00:00"},
                    "night": {"start": "17:00:00", "end_next_day": "08:00:00"},
                },
                "scale_label": "5分钟",
                "query_result_timeout_ms": 20000,
                "download_event_timeout_ms": 120000,
                "login_fill_timeout_ms": 5000,
                "menu_visible_timeout_ms": 20000,
                "iframe_timeout_ms": 15000,
                "start_end_visible_timeout_ms": 5000,
                "page_refresh_retry_count": 1,
                "max_retries": 2,
                "retry_wait_sec": 2,
                "force_iframe_reopen_each_task": True,
                "parallel_by_building": False,
                "site_start_delay_sec": 1,
                "debug_step_log": True,
                "export_button_text": "原样导出",
            },
            "capacity_report": {
                "download": {
                    "template_name": "交接班容量报表",
                    "e_template_name": "每日报表合集",
                    "e_query_result_timeout_ms": 90000,
                    "lookback_minutes": 20,
                    "scale_label": "5分钟",
                    "menu_path": ["报表报告", "数据查询", "即时报表"],
                    "export_button_text": "原样导出",
                },
                "template": {
                    "source_path": "交接班容量报表空模板.xlsx",
                    "sheet_name": "本班组",
                    "output_dir": "D:\\QLDownload\\交接班容量报表输出",
                    "file_name_pattern": "{building}_{date}_交接班容量报表.xlsx",
                    "date_format": "%Y%m%d",
                },
                "parsing": {
                    "sheet_index": 0,
                    "start_row": 4,
                    "col_b": 2,
                    "col_c": 3,
                    "col_d": 4,
                    "col_e": 5,
                    "forward_fill_b": True,
                    "forward_fill_c": True,
                    "value_source": "col_e",
                },
                "oil_cache": {
                    "state_file": "handover_capacity_oil_cache.json",
                },
            },
            "template": {
                "source_path": "交接班日志空模板.xlsx",
                "sheet_name": "交接班日志",
                "file_name_pattern": "{building}_{date}_交接班日志.xlsx",
                "date_format": "%Y%m%d",
                "apply_building_title": True,
                "title_cell": "A1",
                "building_title_pattern": "EA118机房{building_code}栋数据中心交接班日志",
                "building_title_map": {
                    "A楼": "EA118机房A栋数据中心交接班日志",
                    "B楼": "EA118机房B栋数据中心交接班日志",
                    "C楼": "EA118机房C栋数据中心交接班日志",
                    "D楼": "EA118机房D栋数据中心交接班日志",
                    "E楼": "EA118机房E栋数据中心交接班日志",
                },
            },
            "parsing": {
                "sheet_index": 0,
                "start_row": 4,
                "col_b": 2,
                "col_c": 3,
                "col_d": 4,
                "col_e": 5,
                "forward_fill_b": True,
                "forward_fill_c": True,
                "value_source": "col_e",
            },
            "normalize": {
                "b_extract_regex": "([A-Za-z]-\\d{3})",
                "c_extract_regex": "([A-Za-z]\\d-\\d)",
                "fallback": "blank",
            },
            "chiller_mode": {
                "west_keys": ["chiller_mode_1", "chiller_mode_2", "chiller_mode_3"],
                "east_keys": ["chiller_mode_4", "chiller_mode_5", "chiller_mode_6"],
                "priority_order": ["1", "2", "3", "4"],
                "value_map": {"1": "制冷", "2": "预冷", "3": "板换", "4": "停机"},
                "fallback_mode_text": "停机",
            },
            "missing_policy": "blank",
            "shift_roster": {
                "enabled": True,
                "source": {
                    "app_token": "G7oUwGdwaiTmimk8i2ecGTWOn4d",
                    "table_id": "tblRV9KeWFh9xCkm",
                    "page_size": 500,
                    "max_records": 5000,
                },
                "fields": {
                    "duty_date": "排班日期",
                    "building": "机楼",
                    "team": "班组",
                    "shift": "班次",
                    "people_text": "值班人员（实际）",
                },
                "cells": {
                    "current_people": "C3",
                    "next_people": "G3",
                    "next_first_person_cells": ["H52", "H53", "H54", "H55"],
                },
                "match": {
                    "building_mode": "exact_then_code",
                },
                "shift_alias": {
                    "day": ["白班", "day", "DAY"],
                    "night": ["夜班", "night", "NIGHT"],
                },
                "people_split_regex": "[、,/，；;\\s]+",
                "long_day": {
                    "enabled": True,
                    "source": {
                        "app_token": "",
                        "table_id": "tblyyU7BbO4vB1oO",
                        "page_size": 500,
                        "max_records": 5000,
                    },
                    "fields": {
                        "duty_date": "排班日期",
                        "building": "机楼",
                        "shift": "班次",
                        "people_text": "值班人员（实际）",
                    },
                    "shift_value": "长白",
                    "day_cell": "B4",
                    "night_cell": "F4",
                    "prefix": "长白岗：",
                    "rest_text": "/",
                    "match": {
                        "building_mode": "exact_then_code",
                    },
                },
                "engineer_directory": {
                    "enabled": True,
                    "source": {
                        "app_token": "",
                        "table_id": "tblZsQ6UmLdg9a2m",
                        "page_size": 500,
                        "max_records": 5000,
                    },
                    "fields": {
                        "building": "楼栋/专业",
                        "specialty": "专业",
                        "supervisor_text": "主管（文本）",
                        "supervisor_person": "主管",
                        "position": "职位",
                        "recipient_id": "",
                    },
                    "delivery": {
                        "receive_id_type": "user_id",
                        "position_keyword": "设施运维主管",
                    },
                    "match": {
                        "building_mode": "exact_then_code",
                    },
                },
            },
            "event_sections": {
                "enabled": True,
                "source": {
                    "app_token": "D01TwFPyXiJBY6kCBDZcMCGLnSe",
                    "table_id": "tblj9XJLq5QzTAqX",
                    "page_size": 500,
                    "max_records": 5000,
                },
                "duty_window": {
                    "day_start": "09:00:00",
                    "day_end": "18:00:00",
                    "night_start": "18:00:00",
                    "night_end_next_day": "09:00:00",
                    "boundary_mode": "left_closed_right_open",
                },
                "fields": {
                    "event_time": "事件发生时间",
                    "building": "机楼",
                    "event_level": "事件等级",
                    "description": "告警描述",
                    "exclude_checked": "不计入事件",
                    "final_status": "最终状态",
                    "exclude_duration": "事件结束处理时长",
                    "exclude_duration_value": "不计入事件",
                    "to_maint": "是否转检修",
                    "maint_done_time": "检修完成时间",
                    "event_done_time": "事件结束时间",
                },
                "sections": {
                    "new_event": "新事件处理",
                    "history_followup": "历史事件跟进",
                },
                "column_mapping": {
                    "resolve_by_header": True,
                    "header_alias": {
                        "event_level": ["事件等级"],
                        "event_time": ["发生时间"],
                        "description": ["描述", "告警描述"],
                        "work_window": ["作业时间段"],
                        "progress": ["事件处理进展"],
                        "follower": ["跟进人"],
                    },
                    "fallback_cols": {
                        "event_level": "B",
                        "event_time": "C",
                        "description": "D",
                        "work_window": "E",
                        "progress": "F",
                        "follower": "G",
                    },
                },
                "progress_text": {
                    "done": "已完成",
                    "todo": "未完成",
                },
                "cache": {
                    "enabled": True,
                    "state_file": "handover_shared_cache.json",
                    "max_pending": 20000,
                    "max_last_query_ids": 5000,
                },
            },
            "monthly_event_report": {
                "enabled": True,
                "template": {
                    "source_path": "月度事件统计表空模板.xlsx",
                    "change_source_path": "月度变更统计表空模板.xlsx",
                    "output_dir": "D:\\QLDownload\\月度统计表输出\\事件月度统计表",
                    "file_name_pattern": "{building}_{month}_事件月度统计表.xlsx",
                },
                "scheduler": {
                    "enabled": False,
                    "auto_start_in_gui": False,
                    "day_of_month": 1,
                    "run_time": "01:00:00",
                    "check_interval_sec": 30,
                    "state_file": "monthly_event_report_scheduler_state.json",
                },
                "test_delivery": {
                    "receive_id_type": "open_id",
                    "receive_ids": ["ou_902e364a6c2c6c20893c02abe505a7b2"],
                },
            },
            "monthly_change_report": {
                "enabled": True,
                "template": {
                    "source_path": "月度变更统计表空模板.xlsx",
                    "output_dir": "D:\\QLDownload\\月度统计表输出\\变更月度统计表",
                    "file_name_pattern": "{building}_{month}_变更月度统计表.xlsx",
                },
                "scheduler": {
                    "enabled": False,
                    "auto_start_in_gui": False,
                    "day_of_month": 1,
                    "run_time": "01:00:00",
                    "check_interval_sec": 30,
                    "state_file": "monthly_change_report_scheduler_state.json",
                },
            },
            "change_management_section": {
                "enabled": True,
                "source": {
                    "app_token": "D01TwFPyXiJBY6kCBDZcMCGLnSe",
                    "table_id": "tblYodlEKeWzqogu",
                    "page_size": 500,
                    "max_records": 5000,
                },
                "fields": {
                    "building": "楼栋",
                    "start_time": "变更开始时间",
                    "end_time": "变更结束时间",
                    "updated_time": "更新最新的时间",
                    "change_level": "阿里-变更等级",
                    "process_updates": "过程更新时间",
                    "description": "名称",
                    "specialty": "专业",
                },
                "monthly_report_fields": {
                    "building": "楼栋",
                    "change_code": "变更编码",
                    "name": "名称",
                    "location": "位置",
                    "change_level": "智航-变更等级",
                    "status": "变更状态",
                    "start_time": "变更开始时间",
                    "end_time": "变更结束时间",
                },
                "sections": {
                    "change_management": "变更管理",
                },
                "column_mapping": {
                    "resolve_by_header": True,
                    "header_alias": {
                        "change_level": ["变更等级", "事件等级"],
                        "work_window": ["作业时间段"],
                        "description": ["描述", "告警描述"],
                        "executor": ["执行人", "跟进人"],
                    },
                    "fallback_cols": {
                        "change_level": "B",
                        "work_window": "E",
                        "description": "D",
                        "executor": "H",
                    },
                },
                "work_window_text": {
                    "day_anchor": "08:00:00",
                    "day_default_end": "18:30:00",
                    "night_anchor": "18:00:00",
                    "night_default_end_next_day": "08:00:00",
                },
            },
            "exercise_management_section": {
                "enabled": True,
                "source": {
                    "app_token": "D01TwFPyXiJBY6kCBDZcMCGLnSe",
                    "table_id": "tblBrALE11XCicNN",
                    "page_size": 500,
                    "max_records": 5000,
                },
                "fields": {
                    "building": "机楼",
                    "start_time": "演练开始时间",
                    "project": "告警描述",
                },
                "sections": {
                    "exercise_management": "演练管理",
                },
                "fixed_values": {
                    "exercise_type": "计划性演练",
                    "completion": "已完成",
                },
                "column_mapping": {
                    "resolve_by_header": True,
                    "header_alias": {
                        "exercise_type": ["演练类型"],
                        "exercise_item": ["演练项目"],
                        "completion": ["演练完成情况", "完成情况"],
                        "executor": ["执行人", "跟进人"],
                    },
                    "fallback_cols": {
                        "exercise_type": "B",
                        "exercise_item": "C",
                        "completion": "D",
                        "executor": "H",
                    },
                },
            },
            "maintenance_management_section": {
                "enabled": True,
                "source": {
                    "app_token": "D01TwFPyXiJBY6kCBDZcMCGLnSe",
                    "table_id": "tblk7QuEsiE4p3nZ",
                    "page_size": 500,
                    "max_records": 5000,
                },
                "fields": {
                    "building": "楼栋",
                    "start_time": "实际开始时间",
                    "updated_time": "最新更新时间",
                    "actual_end_time": "实际结束时间",
                    "item": "名称",
                    "specialty": "专业",
                },
                "sections": {
                    "maintenance_management": "维护管理",
                },
                "fixed_values": {
                    "vendor_internal": "自维",
                    "vendor_external": "厂维",
                    "completion": "已完成",
                },
                "column_mapping": {
                    "resolve_by_header": True,
                    "header_alias": {
                        "maintenance_item": ["维护总项"],
                        "maintenance_party": ["维护执行方"],
                        "completion": ["维护完成情况", "完成情况"],
                        "executor": ["执行人", "跟进人"],
                    },
                    "fallback_cols": {
                        "maintenance_item": "B",
                        "maintenance_party": "C",
                        "completion": "D",
                        "executor": "H",
                    },
                },
            },
            "other_important_work_section": {
                "enabled": True,
                "source": {
                    "app_token": "D01TwFPyXiJBY6kCBDZcMCGLnSe",
                    "page_size": 500,
                    "max_records": 5000,
                },
                "sections": {
                    "other_important_work": "其他重要工作记录",
                },
                "order": [
                    "power_notice",
                    "device_adjustment",
                    "device_patrol",
                    "device_repair",
                ],
                "column_mapping": {
                    "resolve_by_header": True,
                    "header_alias": {
                        "description": ["描述"],
                        "completion": ["完成情况"],
                        "executor": ["执行人", "跟进人"],
                    },
                    "fallback_cols": {
                        "description": "B",
                        "completion": "F",
                        "executor": "H",
                    },
                },
                "sources": {
                    "power_notice": {
                        "label": "上电通告",
                        "table_id": "tblf2uQrzCWw5eIV",
                        "fields": {
                            "building": "楼栋",
                            "actual_start_time": "实际开始时间",
                            "actual_end_time": "实际结束时间",
                            "description": "名称",
                            "completion": "进度",
                            "specialty": "专业",
                        },
                    },
                    "device_adjustment": {
                        "label": "设备调整",
                        "table_id": "tbleqBZdQu1n8qqK",
                        "fields": {
                            "building": "楼栋",
                            "actual_start_time": "实际开始时间",
                            "actual_end_time": "实际结束时间",
                            "description": "内容",
                            "completion": "进度",
                            "specialty": "专业",
                        },
                    },
                    "device_patrol": {
                        "label": "设备轮巡",
                        "table_id": "tbl0XK1iQ1P6VY5Y",
                        "fields": {
                            "building": "楼栋",
                            "actual_start_time": "实际开始时间",
                            "actual_end_time": "实际结束时间",
                            "description": "内容",
                            "completion": "进度",
                            "specialty": "专业",
                        },
                    },
                    "device_repair": {
                        "label": "设备检修",
                        "table_id": "tblpaHktT0mn0hwg",
                        "fields": {
                            "building": "楼栋",
                            "actual_start_time": "实际开始时间",
                            "actual_end_time": "实际结束时间",
                            "description": "维修故障",
                            "completion": "进度（完成情况）",
                            "specialty": "专业",
                        },
                    },
                },
            },
            "source_data_attachment_export": {
                "enabled": True,
                "source": {
                    "app_token": "ASLxbfESPahdTKs0A9NccgbrnXc",
                    "table_id": "tblF13MQ10PslIdI",
                    "page_size": 500,
                    "max_records": 5000,
                    "delete_batch_size": 200,
                },
                "fields": {
                    "type": "类型",
                    "building": "楼栋",
                    "date": "日期",
                    "shift": "班次",
                    "attachment": "附件",
                },
                "fixed_values": {
                    "type": "动环数据",
                    "shift_text": {
                        "day": "白班",
                        "night": "夜班",
                    },
                },
                "upload_night_shift": True,
                "replace_existing": True,
            },
            "cloud_sheet_sync": {
                "enabled": True,
                "root_wiki_url": "https://vnet.feishu.cn/wiki/WlpWwkhQGi46pEkYbMTcNnOzntb",
                "template_node_token": "QxeYwGTHbiyz9bk2gRAca4nonod",
                "spreadsheet_name_pattern": "南通园区交接班日志-{date_text}{shift_text}",
                "source_sheet_name": "交接班日志",
                "sheet_names": {
                    "A楼": "A楼",
                    "B楼": "B楼",
                    "C楼": "C楼",
                    "D楼": "D楼",
                    "E楼": "E楼",
                },
                "sync_mode": "overwrite_named_sheet",
                "copy": {
                    "values": True,
                    "formulas": True,
                    "styles": True,
                    "merges": True,
                    "row_heights": True,
                    "column_widths": True,
                },
                "request": {
                    "timeout_sec": 20,
                    "max_retries": 3,
                    "retry_backoff_sec": 2,
                },
            },
            "daily_report_bitable_export": {
                "enabled": True,
                "target": {
                    "app_token": "MliKbC3fXa8PXrsndKscmxjdn1g",
                    "table_id": "tblxfd0HA9kDZQ3w",
                    "replace_existing": True,
                    "page_size": 500,
                    "max_records": 5000,
                    "delete_batch_size": 200,
                },
                "fields": {
                    "year": "年度",
                    "date": "日期",
                    "shift": "班次",
                    "report_link": "交接班日报",
                    "screenshots": "日报截图",
                },
                "summary_page_url": "https://vnet.feishu.cn/app/LTjUbmZsTaTFIVsuQSLcUi4Onf4?pageId=pgeZUMIpMDuIIfLA",
                "external_page_url": "https://vnet.feishu.cn/app/LTjUbmZsTaTFIVsuQSLcUi4Onf4?pageId=pgecZCUXaEtvP9Yl",
                "browser_profile_directory": "",
            },
            "template_fixed_fill": {
                "date_cell": "B2",
                "shift_cell": "F2",
                "alarm_total_cell": "B15",
                "alarm_unrecovered_cell": "D15",
                "alarm_accept_desc_cell": "F15",
                "date_text_format": "{year}年{month}月{day}日",
                "shift_text": {"day": "白班", "night": "夜班"},
                "on_alarm_query_fail": {"total": "0", "unrecovered": "0", "accept_desc": "/"},
            },
            "review_ui": {
                "enabled": True,
                "buildings": [
                    {"code": "a", "name": "A楼"},
                    {"code": "b", "name": "B楼"},
                    {"code": "c", "name": "C楼"},
                    {"code": "d", "name": "D楼"},
                    {"code": "e", "name": "E楼"},
                ],
                "fixed_cells": {
                    "header_basic": ["A1", "B2", "F2", "C3", "G3", "B4", "F4"],
                    "metrics_summary": [
                        {"label_cell": "A6", "value_cell": "B6"},
                        {"label_cell": "C6", "value_cell": "D6"},
                        {"label_cell": "E6", "value_cell": "F6"},
                        {"label_cell": "G6", "value_cell": "H6"},
                        {"label_cell": "A7", "value_cell": "B7"},
                        {"label_cell": "C7", "value_cell": "D7"},
                        {"label_cell": "E7", "value_cell": "F7"},
                        {"label_cell": "G7", "value_cell": "H7"},
                        {"label_cell": "A8", "value_cell": "B8"},
                        {"label_cell": "C8", "value_cell": "D8"},
                        {"label_cell": "E8", "value_cell": "F8"},
                        {"label_cell": "A9", "value_cell": "B9"},
                        {"label_cell": "C9", "value_cell": "D9"},
                        {"label_cell": "E9", "value_cell": "F9"},
                        {"label_cell": "G9", "value_cell": "H9"},
                        {"label_cell": "A10", "value_cell": "B10"},
                        {"label_cell": "C10", "value_cell": "D10"},
                        {"label_cell": "E10", "value_cell": "F10"},
                        "B15",
                        "D15",
                        "F15",
                        "H52",
                        "H53",
                        "H54",
                        "H55",
                    ],
                    "cabinet_power_info": ["B13", "D13", "F13", "H13"],
                },
                "autosave_debounce_ms": 800,
                "poll_interval_sec": 5,
                "bind_latest_session": True,
                "public_base_url": "",
                "section_hidden_columns": ["I"],
                "cabinet_power_defaults_by_building": {},
                "footer_inventory_defaults_by_building": {},
                "review_link_recipients_by_building": {},
            },
            "cell_rules": {
                "default_rows": [
                    {
                        "id": "cold_temp_max",
                        "enabled": True,
                        "target_cell": "B9",
                        "rule_type": "aggregate",
                        "d_keywords": ["冷通道温度"],
                        "match_mode": "contains_casefold",
                        "agg": "max",
                        "template": "{value}℃/{b_norm} {c_norm}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "cold_humi_max",
                        "enabled": True,
                        "target_cell": "D9",
                        "rule_type": "aggregate",
                        "d_keywords": ["冷通道湿度"],
                        "match_mode": "contains_casefold",
                        "agg": "max",
                        "template": "{value}%/{b_norm} {c_norm}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "cold_temp_min",
                        "enabled": True,
                        "target_cell": "F9",
                        "rule_type": "aggregate",
                        "d_keywords": ["冷通道温度"],
                        "match_mode": "contains_casefold",
                        "agg": "min",
                        "template": "{value}℃/{b_norm} {c_norm}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "cold_humi_min",
                        "enabled": True,
                        "target_cell": "H9",
                        "rule_type": "aggregate",
                        "d_keywords": ["冷通道湿度"],
                        "match_mode": "contains_casefold",
                        "agg": "min",
                        "template": "{value}%/{b_norm} {c_norm}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "tr_load_max",
                        "enabled": True,
                        "target_cell": "B10",
                        "rule_type": "aggregate",
                        "d_keywords": ["负载率"],
                        "d_regex": ".*负载率",
                        "group_contains": "TR",
                        "match_mode": "contains_casefold",
                        "agg": "max",
                        "template": "{value}%/{d_name}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "ups_load_max",
                        "enabled": True,
                        "target_cell": "D10",
                        "rule_type": "aggregate",
                        "d_keywords": ["负载率"],
                        "d_regex": ".*负载率",
                        "group_contains": "UPS",
                        "match_mode": "contains_casefold",
                        "agg": "max",
                        "template": "{value}%/{d_name}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "hvdc_load_max",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "aggregate",
                        "d_keywords": ["HVDC", "负载率"],
                        "d_regex": ".*(HVDC.*负载率|负载率.*HVDC).*",
                        "group_contains": "HVDC",
                        "match_mode": "contains_casefold",
                        "agg": "max",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "battery_backup_min",
                        "enabled": True,
                        "target_cell": "F10",
                        "rule_type": "aggregate",
                        "d_keywords": ["电池放电后备时间"],
                        "match_mode": "contains_casefold",
                        "agg": "min",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "oil_backup_time",
                        "enabled": True,
                        "target_cell": "H6",
                        "rule_type": "direct",
                        "d_keywords": ["油量后备时间", "燃油后备时间"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "chiller_mode_1",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["1号冷机模式"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "chiller_mode_2",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["2号冷机模式"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "chiller_mode_3",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["3号冷机模式"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "chiller_mode_4",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["4号冷机模式"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "chiller_mode_5",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["5号冷机模式"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "chiller_mode_6",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["6号冷机模式"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "west_tank_time",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["西区蓄冷罐放冷时间"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "east_tank_time",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["东区蓄冷罐放冷时间"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "ring_124",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["124-冷冻水供水环管温度", "124-冷冻水供水温度", "西区冷冻水供水环管温度"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "ring_150",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "direct",
                        "d_keywords": ["150-冷冻水供水环管温度", "150-冷冻水供水温度", "东区冷冻水供水环管温度"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "chilled_supply_temp_max",
                        "enabled": True,
                        "target_cell": "",
                        "rule_type": "aggregate",
                        "d_keywords": ["冷冻水供水温度"],
                        "match_mode": "contains_casefold",
                        "agg": "max",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "tank_backup",
                        "enabled": True,
                        "target_cell": "F8",
                        "rule_type": "computed",
                        "d_keywords": [],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "西区{west}/东区{east}",
                        "computed_op": "tank_backup",
                        "params": {},
                    },
                    {
                        "id": "outdoor_temp",
                        "enabled": True,
                        "target_cell": "B7",
                        "rule_type": "direct",
                        "d_keywords": ["室外温度", "室外干球温度"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "wet_bulb",
                        "enabled": True,
                        "target_cell": "D7",
                        "rule_type": "direct",
                        "d_keywords": ["室外湿球温度"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "ring_supply_temp",
                        "enabled": True,
                        "target_cell": "H7",
                        "rule_type": "computed",
                        "d_keywords": [],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "西区{west}℃/东区{east}℃",
                        "computed_op": "ring_supply_temp",
                        "params": {},
                    },
                    {
                        "id": "chiller_mode_summary",
                        "enabled": True,
                        "target_cell": "F7",
                        "rule_type": "computed",
                        "d_keywords": [],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "西区{west_mode}/东区{east_mode}",
                        "computed_op": "chiller_mode_summary",
                        "params": {},
                    },
                    {
                        "id": "water_pool_backup_time",
                        "enabled": True,
                        "target_cell": "D8",
                        "rule_type": "direct",
                        "d_keywords": ["水池后备时间"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "city_water_pressure",
                        "enabled": True,
                        "target_cell": "B8",
                        "rule_type": "direct",
                        "d_keywords": ["市政补水管压力", "市政压力"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "pue",
                        "enabled": True,
                        "target_cell": "B6",
                        "rule_type": "direct",
                        "d_keywords": ["PUE", "实时PUE", "实时pue"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "city_power",
                        "enabled": True,
                        "target_cell": "D6",
                        "rule_type": "direct",
                        "d_keywords": ["市电进线总功率", "市电总功率", "D楼总功率"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                    {
                        "id": "it_power",
                        "enabled": True,
                        "target_cell": "F6",
                        "rule_type": "direct",
                        "d_keywords": ["IT总功率", "IT功率", "二三四层功率和", "IT功率和"],
                        "match_mode": "contains_casefold",
                        "agg": "first",
                        "template": "{value}",
                        "computed_op": "",
                        "params": {},
                    },
                ],
                "building_rows": {},
            },
        },
        "day_metric_upload": {
            "scheduler": {
                "enabled": False,
                "auto_start_in_gui": False,
                "interval_minutes": 60,
                "check_interval_sec": 30,
                "retry_failed_on_next_tick": True,
                "state_file": "day_metric_upload_scheduler_state.json",
            },
            "behavior": {
                "basic_retry_attempts": 3,
                "basic_retry_backoff_sec": 2,
                "network_retry_attempts": 5,
                "network_retry_backoff_sec": 2,
                "alert_after_attempts": 5,
            },
            "target": {
                "source": {
                    "app_token": "ASLxbfESPahdTKs0A9NccgbrnXc",
                    "table_id": "tblAHGF8mV6U9jid",
                    "create_batch_size": 200,
                },
                "fields": {
                    "type": "类型",
                    "building": "楼栋",
                    "date": "日期",
                    "value": "数值",
                    "position_code": "位置/编号",
                },
                "missing_value_policy": "zero",
            },
        },
        "alarm_export": {
            "scheduler": {
                "enabled": False,
                "auto_start_in_gui": False,
                "run_time": "08:10:00",
                "check_interval_sec": 30,
                "catch_up_if_missed": False,
                "retry_failed_in_same_period": True,
                "state_file": "alarm_event_upload_scheduler_state.json",
            },
            "feishu": {
                "app_token": "",
                "table_id": "",
                "page_size": 500,
                "delete_batch_size": 500,
                "create_batch_size": 200,
            },
            "shared_source_upload": {
                "replace_existing_on_full": True,
            },
        },
        "manual_upload_gui": {
            "enabled": True,
        },
    },
}


def deep_merge_defaults(raw: Any, defaults: Any) -> Any:
    if isinstance(defaults, dict):
        src = raw if isinstance(raw, dict) else {}
        out: Dict[str, Any] = {}
        for key, default_value in defaults.items():
            out[key] = deep_merge_defaults(src.get(key), default_value)
        for key, value in src.items():
            if key not in out:
                out[key] = copy.deepcopy(value)
        return out
    if isinstance(defaults, list):
        if isinstance(raw, list):
            return copy.deepcopy(raw)
        return copy.deepcopy(defaults)
    if raw is None:
        return copy.deepcopy(defaults)
    return copy.deepcopy(raw)
